import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import Sidebar from "./components/sideBar/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen w-full bg-[#e9ecef] overflow-hidden select-none">
          <div className="hidden bg-white sm:block transition-all h-full">
            <Sidebar />
          </div>
          <div className="flex flex-1 flex-col h-full overflow-hidden bg-[#e9ecef]">
            <Header />
            <div className="flex-1 overflow-y-auto bg-[#e9ecef]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
